import React, { useState, useEffect } from 'react';
import { X, Mail, Loader2, CheckCircle, Copy, AlertTriangle } from 'lucide-react';
import { useGovernanceApi } from '../hooks/useGovernanceApi';

const EmailModal = ({ issue, onClose }) => {
  const { draftComplianceEmail } = useGovernanceApi();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [draft, setDraft] = useState(null);
  const [copySuccess, setCopySuccess] = useState(false);

  useEffect(() => {
    if (issue) {
      generateDraft();
    }
  }, [issue]);

  const generateDraft = async () => {
    setLoading(true);
    setError(null);
    const result = await draftComplianceEmail(issue);
    if (result) {
      setDraft(result);
    } else {
      setError("Failed to generate email draft. Ensure AI service is running.");
    }
    setLoading(false);
  };

  const handleCopy = () => {
    if (draft) {
      const emailContent = `Subject: ${draft.subject}\n\n${draft.body}`;
      navigator.clipboard.writeText(emailContent);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    }
  };

  if (!issue) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900/50 backdrop-blur-sm p-4">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl overflow-hidden flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-200 flex justify-between items-center bg-gray-50">
          <h3 className="text-lg font-semibold text-gray-900 flex items-center">
            <Mail className="h-5 w-5 mr-2 text-blue-600" />
            AI Draft: Compliance Notice
          </h3>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-500 transition-colors">
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto flex-1">
          {loading && (
            <div className="flex flex-col items-center justify-center py-12">
              <Loader2 className="h-10 w-10 text-blue-600 animate-spin mb-4" />
              <p className="text-gray-600 font-medium">ESGenius AI is drafting the email...</p>
              <p className="text-sm text-gray-500 mt-1">Analyzing issue severity and policy context.</p>
            </div>
          )}

          {error && (
            <div className="bg-red-50 border border-red-200 rounded-md p-4 text-center">
              <AlertTriangle className="h-8 w-8 text-red-500 mx-auto mb-2" />
              <p className="text-sm font-medium text-red-800">{error}</p>
              <button onClick={generateDraft} className="mt-3 px-3 py-1.5 bg-white border border-red-200 text-red-700 text-sm font-medium rounded hover:bg-red-50">Try Again</button>
            </div>
          )}

          {!loading && !error && draft && (
            <div className="space-y-4">
              <div className="bg-gray-50 rounded-md p-3 border border-gray-200 flex flex-col">
                <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Subject</span>
                <span className="text-sm font-medium text-gray-900">{draft.subject}</span>
              </div>
              
              <div className="bg-white rounded-md p-4 border border-gray-200 min-h-[250px] whitespace-pre-wrap text-sm text-gray-700 font-serif leading-relaxed">
                {draft.body}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        {!loading && !error && (
          <div className="px-6 py-4 border-t border-gray-200 bg-white flex justify-between items-center">
            <p className="text-xs text-gray-500 italic">This email was generated by ESGenius AI. Review before sending.</p>
            <div className="flex space-x-3">
              <button 
                onClick={handleCopy}
                className="flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 transition-colors"
              >
                {copySuccess ? <CheckCircle className="h-4 w-4 mr-2 text-green-500" /> : <Copy className="h-4 w-4 mr-2" />}
                {copySuccess ? 'Copied!' : 'Copy to Clipboard'}
              </button>
              <button 
                onClick={onClose}
                className="px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 transition-colors"
              >
                Done
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default EmailModal;
