import React, { useState, useEffect } from 'react';
import { X, Mail, Loader2, Copy, CheckCircle, Send } from 'lucide-react';
import { useGovernanceApi } from '../hooks/useGovernanceApi';

const EmailModal = ({ issue, onClose }) => {
  const { draftComplianceEmail } = useGovernanceApi();
  const [loading, setLoading] = useState(true);
  const [emailData, setEmailData] = useState(null);
  const [error, setError] = useState(null);
  const [copySuccess, setCopySuccess] = useState(false);

  useEffect(() => {
    const generateEmail = async () => {
      setLoading(true);
      const data = await draftComplianceEmail(issue.id);
      if (data) {
        setEmailData(data);
      } else {
        setError('Failed to generate email. Please try again.');
      }
      setLoading(false);
    };

    if (issue) {
      generateEmail();
    }
  }, [issue, draftComplianceEmail]);

  if (!issue) return null;

  const handleCopy = () => {
    if (emailData) {
      const textToCopy = `Subject: ${emailData.subject}\n\n${emailData.body}`;
      navigator.clipboard.writeText(textToCopy);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900/50 backdrop-blur-sm">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl mx-4 overflow-hidden flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div className="flex items-center">
            <Mail className="h-5 w-5 text-blue-600 mr-2" />
            <h3 className="text-lg font-semibold text-gray-900">AI Compliance Email Draft</h3>
          </div>
          <button 
            onClick={onClose}
            className="text-gray-400 hover:text-gray-500 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Body */}
        <div className="p-6 flex-1 overflow-y-auto bg-gray-50">
          
          {loading && (
            <div className="flex flex-col items-center justify-center py-12">
              <Loader2 className="h-10 w-10 text-blue-600 animate-spin mb-4" />
              <p className="text-gray-600 font-medium">ESGenius AI is drafting the email...</p>
              <p className="text-sm text-gray-500 mt-1">Analyzing issue severity and policy context.</p>
            </div>
          )}

          {error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-center">
              <p className="text-red-700 font-medium mb-4">{error}</p>
              <button 
                onClick={onClose}
                className="px-4 py-2 bg-white border border-gray-300 rounded-md text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50"
              >
                Close
              </button>
            </div>
          )}

          {!loading && emailData && (
            <div className="space-y-4">
              <div className="bg-white border border-gray-200 rounded-lg overflow-hidden shadow-sm">
                <div className="bg-gray-50 px-4 py-3 border-b border-gray-200 text-sm">
                  <span className="text-gray-500 font-medium w-16 inline-block">To:</span>
                  <span className="text-gray-900">Employee #{issue.owner_employee_id}</span>
                </div>
                <div className="bg-gray-50 px-4 py-3 border-b border-gray-200 text-sm">
                  <span className="text-gray-500 font-medium w-16 inline-block">Subject:</span>
                  <span className="text-gray-900 font-medium">{emailData.subject}</span>
                </div>
                <div className="p-4">
                  <textarea 
                    className="w-full min-h-[250px] text-sm text-gray-700 border-none resize-none focus:ring-0 p-0"
                    defaultValue={emailData.body}
                  />
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        {!loading && !error && (
          <div className="px-6 py-4 border-t border-gray-200 bg-white flex justify-between items-center">
            <p className="text-xs text-gray-500 italic">This email was generated by ESGenius AI. Review before sending.</p>
            <div className="flex space-x-3">
              <button 
                onClick={handleCopy}
                className="flex items-center px-4 py-2 bg-white border border-gray-300 rounded-md text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 transition-colors"
              >
                {copySuccess ? <CheckCircle className="h-4 w-4 mr-2 text-green-600" /> : <Copy className="h-4 w-4 mr-2" />}
                {copySuccess ? 'Copied' : 'Copy Text'}
              </button>
              <button 
                className="flex items-center px-4 py-2 bg-blue-600 border border-transparent rounded-md text-sm font-medium text-white shadow-sm hover:bg-blue-700 transition-colors"
              >
                <Send className="h-4 w-4 mr-2" /> Open in Client
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default EmailModal;
